spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_Ms
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    prefix: classpath:/templates/   # Location of your templates
    suffix: .html                   # File extension for your templates
    cache: false

    jwt:
      secret: 23467912f3288ec1873e25eee653f6fbaafe39c3751435afe56faf01fb2d34c7




  mail:
    host: smtp.gmail.com
    port: 587
    username: joshuasirpatrickmumba@gmail.com
    password: toly wxmt obmc xfoq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account:
    sid: AC7f2b62835e802d83cdb7ae78a0fbe9ea
  auth:
    token: e23fd669156d660dd62853939d6e1ceb
  phone:
    number: +15677575781

