spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_Ms
    username: ${db_username}
    password: ${db_password}
  jpa:
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/   # Location of your templates
    suffix: .html                   # File extension for your templates
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email_user}
    password: ${email_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account:
    sid: ${sid}
  auth:
    token: ${token}
  phone:
    number: +15677575781
